alias git="TERM=xterm git"
alias gitf="git flow"
alias gitfi="git flow init"
alias gitff="git flow feature"
alias gitfb="git flow bugfix"
alias gitfr="git flow release"
alias gitfh="git flow hotfix"
alias gitfs="git flow support"
alias gitfl="git flow log"
alias gitfv="git flow version"
alias gitfc="git flow config"
