#!/bin/bash

echo '
Alias:
    git co "checkout"
    git cm "commit -s -a"
    git ss "status"
    git br "branch -a"
    git cp "cherry-pick -s -x"
    git lr "ls-remote origin"
    git ls "log --color --graph"

    lgit   "git add & git commit & git push"

    gitf   "git flow"
    gitfi  "git flow init"
    gitff  "git flow feature"
    gitfb  "git flow bugfix"
    gitfr  "git flow release"
    gitfh  "git flow hotfix"
    gitfs  "git flow support"
    gitfl  "git flow log"
    gitfv  "git flow version"
    gitfc  "git flow config"

commit message:
    feat：    新功能（feature）
    fix：     修补bug
    docs：    文档（documentation）
    style：   格式（不影响代码运行的变动）
    refactor：重构（即不是新增功能，也不是修改bug的代码变动）
    test：    增加测试
    chore：   构建过程或辅助工具的变动
'
