#!/bin/bash

echo "
Alias:
    go-i go-init       初始化go项目, 并进入项目的虚拟环境
    gos  go-shell      进入指定go项目的虚拟环境
    gog  glide get     下载指定远程库
    goi  glide install 安装项目依赖
    gou  glide update  升级项目依赖
"
