#!/bin/bash

# Author        : Tony Bian <biantonghe@gmail.com>
# Last Modified : 2019-01-16 14:17
# Filename      : hostpwd.sh

WORKSPACE=$(docker inspect -f '{{println}}{{range .Mounts}}{{.Source}} {{.Destination}}{{println}}{{end}}' $(hostname) | grep -e "/workspace$" | awk '{print $1}')

CURRENT=$(pwd | awk -F "/" '{print $NF}')

if [[ ${PWD} == ${WORKSPACE} ]]; then
    HOST_PATH=${WORKSPACE}
else
    HOST_PATH=${WORKSPACE}/${CURRENT}
fi

echo ${HOST_PATH}
